# Generated by Django 4.0.5 on 2023-03-17 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yoga', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='info',
            field=models.CharField(default='Discount', max_length=300),
        ),
    ]
