# Generated by Django 4.0.5 on 2023-03-17 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yoga', '0002_alter_slider_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='discount',
            field=models.CharField(default='Discount', max_length=300),
        ),
        migrations.AlterField(
            model_name='slider',
            name='info',
            field=models.CharField(default='Marka İsimi', max_length=300),
        ),
    ]
