# Generated by Django 4.0.5 on 2023-03-28 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yoga', '0004_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='slug',
            field=models.SlugField(default=21, max_length=200),
            preserve_default=False,
        ),
    ]
