# Generated by Django 4.0.5 on 2023-03-29 18:38

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yoga', '0006_alter_slider_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='mini_info',
            field=ckeditor_uploader.fields.RichTextUploadingField(default=21),
            preserve_default=False,
        ),
    ]
