# Generated by Django 4.0.5 on 2023-04-18 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yoga', '0009_kvvk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(blank=True, upload_to='products/%y/%m/%d', verbose_name='Resim : (550x350)'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='list',
            field=models.ImageField(blank=True, upload_to='products/%y/%m/%d', verbose_name='Resim : (850x530)'),
        ),
    ]
