# Generated by Django 4.0.5 on 2023-04-23 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yoga', '0010_alter_blog_image_alter_blog_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='info_two',
        ),
        migrations.RemoveField(
            model_name='about',
            name='title_two',
        ),
    ]
