# Generated by Django 4.0.5 on 2023-04-30 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yoga', '0011_remove_about_info_two_remove_about_title_two'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slider',
            name='discount',
        ),
    ]
