# Generated by Django 4.0.5 on 2023-04-30 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yoga', '0012_remove_slider_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='image',
            field=models.ImageField(blank=True, upload_to='products/%y/%m/%d', verbose_name='Resim : (1015x765)'),
        ),
    ]
