# Generated by Django 3.0.5 on 2021-07-17 21:24

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=20)),
                ('slug', models.SlugField(max_length=20, unique=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inside_category', to='shop.Category')),
            ],
            options={
                'verbose_name_plural': 'categories',
                'unique_together': {('slug', 'parent')},
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_no', models.CharField(default='Ürün Kodu Giriniz', max_length=25)),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('slug', models.SlugField(max_length=200)),
                ('image', models.ImageField(blank=True, upload_to='products/%y/%m/%d')),
                ('image2', models.ImageField(blank=True, upload_to='products/%y/%m/%d')),
                ('image3', models.ImageField(blank=True, upload_to='products/%y/%m/%d')),
                ('image4', models.ImageField(blank=True, upload_to='products/%y/%m/%d')),
                ('info', models.TextField(default='Ürün Aaçıklama')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True)),
                ('shop', ckeditor_uploader.fields.RichTextUploadingField(blank=True)),
                ('price', models.DecimalField(decimal_places=0, max_digits=10)),
                ('normal_price', models.CharField(db_index=True, default='SOME STRING', max_length=4)),
                ('discount', models.CharField(db_index=True, default='SOME STRING', max_length=4)),
                ('stock', models.PositiveIntegerField()),
                ('available', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('seo', models.CharField(default='Seo için Bilgi Giriniz.', max_length=500)),
                ('key', models.CharField(default='Keyword için Giriş', max_length=550)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='shop.Category')),
            ],
            options={
                'ordering': ('created',),
                'index_together': {('id', 'slug')},
            },
        ),
    ]
