# Generated by Django 4.0.5 on 2023-03-17 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_category_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='noDropDown',
            new_name='bestsale',
        ),
        migrations.RemoveField(
            model_name='product',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image3',
        ),
        migrations.RemoveField(
            model_name='product',
            name='normal_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='updated',
        ),
        migrations.AddField(
            model_name='product',
            name='one',
            field=models.TextField(default='Ürün Aaçıklama'),
        ),
        migrations.AddField(
            model_name='product',
            name='three',
            field=models.TextField(default='Ürün Aaçıklama'),
        ),
        migrations.AddField(
            model_name='product',
            name='two',
            field=models.TextField(default='Ürün Aaçıklama'),
        ),
    ]
