# Generated by Django 4.0.5 on 2023-03-28 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_rename_bestsale_product_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='kid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='saler',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, upload_to='products/%y/%m/%d', verbose_name='Check İMAGE'),
        ),
    ]
