# Generated by Django 4.0.5 on 2023-03-28 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_product_kid_product_saler_alter_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='kid',
            new_name='news',
        ),
    ]
