# Generated by Django 4.0.5 on 2023-03-28 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_rename_kid_product_news'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='news',
        ),
        migrations.RemoveField(
            model_name='product',
            name='saler',
        ),
    ]
