# Generated by Django 4.0.5 on 2023-03-28 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_remove_product_news_remove_product_saler'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='news',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='saler',
            field=models.BooleanField(default=False),
        ),
    ]
