# Generated by Django 4.0.5 on 2023-03-28 19:20

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_product_news_product_saler'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rules',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.CharField(db_index=True, max_length=200)),
                ('sss', ckeditor_uploader.fields.RichTextUploadingField(blank=True)),
            ],
        ),
    ]
