# Generated by Django 4.0.5 on 2023-04-30 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_rules'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='saler',
        ),
    ]
