# Generated by Django 4.0.5 on 2023-04-30 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_remove_product_saler'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='one',
        ),
        migrations.RemoveField(
            model_name='product',
            name='three',
        ),
        migrations.RemoveField(
            model_name='product',
            name='two',
        ),
    ]
