# Generated by Django 4.0.5 on 2023-04-30 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_remove_product_one_remove_product_three_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='list_image',
            field=models.ImageField(blank=True, upload_to='products/%y/%m/%d', verbose_name='370x410'),
        ),
    ]
