# Generated by Django 3.2 on 2023-05-03 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, verbose_name='Name')),
                ('image', models.ImageField(blank=True, upload_to='products/%y/%m/%d', verbose_name='467x459')),
                ('title', models.CharField(blank=True, max_length=50, verbose_name='Başlık')),
                ('info', models.CharField(blank=True, max_length=50, verbose_name='İnfo')),
                ('link', models.CharField(blank=True, max_length=50, verbose_name='Yönledirme')),
                ('vercital', models.ImageField(blank=True, upload_to='products/%y/%m/%d', verbose_name='184x322')),
            ],
        ),
    ]
