# Generated by Django 3.2 on 2023-05-06 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='technic',
            field=models.ImageField(blank=True, upload_to='products/%y/%m/%d', verbose_name='Check İMAGE'),
        ),
    ]
