# Generated by Django 3.2 on 2023-05-06 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_product_technic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
