# Generated by Django 3.2 on 2023-05-07 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_remove_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='technic',
            field=models.ImageField(blank=True, upload_to='products/%y/%m/%d', verbose_name='Teknik Çizim'),
        ),
    ]
