# Generated by Django 3.0.5 on 2021-07-24 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20210724_1410'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='day',
        ),
        migrations.RemoveField(
            model_name='order',
            name='hotel',
        ),
        migrations.RemoveField(
            model_name='order',
            name='room',
        ),
    ]
