# Generated by Django 3.0.5 on 2021-08-02 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20210724_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='tokenCheck',
            field=models.CharField(default=False, max_length=36, verbose_name='Token check:'),
        ),
    ]
