# Generated by Django 4.0.5 on 2022-07-14 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20210802_2059'),
    ]

    operations = [
        migrations.CreateModel(
            name='SenderData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(default=False, max_length=36, verbose_name='User:')),
                ('order', models.CharField(default=False, max_length=36, verbose_name='Order:')),
                ('tokenCheck', models.CharField(default=False, max_length=36, verbose_name='Token check:')),
            ],
        ),
    ]
