# Generated by Django 4.0.5 on 2023-03-22 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_reservation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='adress',
        ),
        migrations.AddField(
            model_name='reservation',
            name='adres',
            field=models.CharField(db_index=True, default='Adress', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='city',
            field=models.CharField(db_index=True, default='City', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='email',
            field=models.CharField(db_index=True, default='Mail', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='lastname',
            field=models.CharField(blank=True, db_index=True, default='Lastname', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='name',
            field=models.CharField(blank=True, db_index=True, default='Name', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='phone',
            field=models.CharField(blank=True, db_index=True, default='Phone', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='tc',
            field=models.CharField(blank=True, db_index=True, default='TC', max_length=100, null=True),
        ),
    ]
