# Generated by Django 4.0.5 on 2023-03-22 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_reservation_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=510, verbose_name='status:')),
                ('systemtime', models.CharField(max_length=510, verbose_name='systemtime:')),
                ('conversationİd', models.CharField(max_length=510, verbose_name='conversationİd:')),
                ('price', models.CharField(max_length=510, verbose_name='price:')),
                ('paidPrice', models.CharField(max_length=510, verbose_name='paidPrice:')),
                ('paymentid', models.CharField(max_length=510, verbose_name='paymentid:')),
                ('binNumber', models.CharField(max_length=510, verbose_name='binNumber:')),
                ('result_token', models.CharField(max_length=510, verbose_name='result_token:')),
                ('payment_token', models.CharField(max_length=510, verbose_name='payment_token:')),
            ],
        ),
        migrations.CreateModel(
            name='UserTokenData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userlast', models.CharField(max_length=510)),
                ('usertoken', models.CharField(max_length=510)),
            ],
        ),
        migrations.CreateModel(
            name='WebhookData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paymentConversation', models.CharField(max_length=510, verbose_name='paymentConversation:')),
                ('merchant', models.CharField(max_length=510, verbose_name='merchant:')),
                ('webhooktoken', models.CharField(max_length=510, verbose_name='webhooktoken:')),
                ('status', models.CharField(max_length=510, verbose_name='status:')),
                ('iyziReferenceCode', models.CharField(max_length=510, verbose_name='iyziReferenceCode:')),
                ('iyziEventType', models.CharField(max_length=510, verbose_name='iyziEventType:')),
                ('iyziEventTime', models.CharField(max_length=510, verbose_name='iyziEventTime:')),
            ],
        ),
    ]
